[global]
#        log file = /persist/samba/%m
        log file = /dev/null
        log level = 1
        server role = standalone server
	map to guest = bad user

[usb1]
        # This share requires authentication to access
        path = /mnt/usb1
 	guest only = yes
	public = yes
        force user = root
        force group = root
#        read only = no
        writable = yes
        
[usb2]
        # This share requires authentication to access
        path = /mnt/usb2
        guest only = yes
	public = yes
        force user = root
        force group = root
 #       read only = no
        writable = yes

[usb3]
        # This share requires authentication to access
        path = /mnt/usb3
        guest only = yes
	public = yes        
        force user = root
        force group = root
#        read only = no
        writable = yes
        
[usb4]
        # This share requires authentication to access
        path = /mnt/usb4
        guest only = yes
	public = yes        
        force user = root
        force group = root
#        read only = no
        writable = yes
